name: Lint and test

on:
  push:
    branches:
    - '*'

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        architecture: 'x64'
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    - name: Install the project dependencies
      run: poetry install
    - name: Run linter checks
      run: poetry run make lint
      continue-on-error: true
    - name: Run tests
      run: poetry run make test
